/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class Dashboard extends javax.swing.JFrame {

    private static String adname, adpass, type = "member", types;

    private static String filepath2 = "src\\guiapp\\Data.json";
    private static JSONParser jsonParser2 = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();
    private static JSONObject user = new JSONObject();

    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Addbttn = new javax.swing.JButton();
        Deletebttn = new javax.swing.JButton();
        Updatebttn = new javax.swing.JButton();
        Logoutbttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\zelxs\\OneDrive\\Desktop\\Into the Neverwhere - Masha Shango.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Addbttn.setText("Add Student");
        Addbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbttnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 100, 109, -1));

        Deletebttn.setText("Delete Student");
        Deletebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebttnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 166, -1, -1));

        Updatebttn.setText("Update Student");
        Updatebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebttnActionPerformed(evt);
            }
        });
        getContentPane().add(Updatebttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        Logoutbttn.setText("Logout");
        Logoutbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbttnActionPerformed(evt);
            }
        });
        getContentPane().add(Logoutbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 166, 113, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("WELCOME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\zelxs\\OneDrive\\Desktop\\Into the Neverwhere - Masha Shango.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebttnActionPerformed
        Update y = new Update(); // // This will make updatebutton can be used and iniatilized and be transfered to update window
        y.setVisible(true);
    }//GEN-LAST:event_UpdatebttnActionPerformed

    private void LogoutbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbttnActionPerformed
        this.dispose(); // close the current window
        new Login().setVisible(true); // open the new login window
    }//GEN-LAST:event_LogoutbttnActionPerformed

    private void AddbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbttnActionPerformed
        Add z = new Add(); // This will make addbutton can be used and iniatilized and be transfered to add window
        z.setVisible(true);
    }//GEN-LAST:event_AddbttnActionPerformed

    private void DeletebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebttnActionPerformed
        Delete a = new Delete(); // This will make deletebutton can be used and iniatilized and be transfered to delete window
        a.setVisible(true);
    }//GEN-LAST:event_DeletebttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // This line will iterate all of the available look and feel and it set the ui theme to nimbus if its available
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

            // this line is for when nimbus is not found or cannot be used the program will prompt errors
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbttn;
    private javax.swing.JButton Deletebttn;
    private javax.swing.JButton Logoutbttn;
    private javax.swing.JButton Updatebttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
