/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class Update extends javax.swing.JFrame {

    private static String usname, pass, type = "admin";

    private static String filepath = "src\\Data.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jusername = new javax.swing.JLabel();
        jpasswordfield = new javax.swing.JLabel();
        juser = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        Updatebttn = new javax.swing.JButton();
        Clearbttn = new javax.swing.JButton();
        Backbttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jnewuser = new javax.swing.JTextField();
        jnewpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 35, 37, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Update Student");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jusername.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jusername.setForeground(new java.awt.Color(0, 0, 0));
        jusername.setText("username");
        jPanel1.add(jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 78, -1, -1));

        jpasswordfield.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jpasswordfield.setForeground(new java.awt.Color(0, 0, 0));
        jpasswordfield.setText("password");
        jPanel1.add(jpasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 112, -1, -1));
        jPanel1.add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 75, 229, -1));

        jpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassActionPerformed(evt);
            }
        });
        jPanel1.add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 109, 229, -1));

        Updatebttn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Updatebttn.setText("Update");
        Updatebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebttnActionPerformed(evt);
            }
        });
        jPanel1.add(Updatebttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        Clearbttn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        Clearbttn.setText("Clear");
        Clearbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbttnActionPerformed(evt);
            }
        });
        jPanel1.add(Clearbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        Backbttn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        Backbttn.setText("Back");
        Backbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbttnActionPerformed(evt);
            }
        });
        jPanel1.add(Backbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("new username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 161, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("new password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 195, 90, -1));
        jPanel1.add(jnewuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 158, 229, -1));
        jPanel1.add(jnewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 192, 229, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 41, 37, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\zelxs\\OneDrive\\Desktop\\Into the Neverwhere - Masha Shango.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbttnActionPerformed
        // This will erase all the typed data on the textfield if you click the clear button
        juser.setText("");
        jpass.setText("");
        jnewuser.setText("");
        jnewpass.setText("");
    }//GEN-LAST:event_ClearbttnActionPerformed

    private void UpdatebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebttnActionPerformed

        // This will turn the existing username and password to be updated
        try {
            filecheck();
            String currentUsername = juser.getText().trim();
            String newUsername = jnewuser.getText().trim();
            String newPassword = jnewpass.getText().trim();
            boolean found = false;

            // This will check the entered user data if its a existing data and if is then it will be updated
            for (int i = 0; i < userlist.size(); i++) {
                JSONObject user = (JSONObject) userlist.get(i);
                if (user.get("username").equals(currentUsername)) {
                    user.put("username", newUsername.isEmpty() ? currentUsername : newUsername);
                    user.put("password", newPassword.isEmpty() ? user.get("password") : newPassword);
                    found = true;
                    break; // exit the loop
                }
            }

            // This will prompt a message if the user data was updated or cannot be found
            if (found) {
                record.put("users", userlist);
                JOptionPane.showMessageDialog(this, "User updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "User not found.");
            }

            // This will save the update data
            save();
        } catch (IOException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "An error occurred.");
        } catch (ParseException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose(); // Close the current window
        Dashboard e = new Dashboard(); // open the dashboard window
        e.setVisible(true);
    }//GEN-LAST:event_UpdatebttnActionPerformed

    private void BackbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbttnActionPerformed
        this.dispose(); // Close the current window
        Dashboard e = new Dashboard(); // open the dashboard window
        e.setVisible(true);
    }//GEN-LAST:event_BackbttnActionPerformed

    private void jpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // // This line will iterate all of the available look and feel and it set the ui theme to nimbus if its available
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

            // // this line is for when nimbus is not found or cannot be used the program will prompt errors
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    public void filecheck() throws FileNotFoundException, IOException, ParseException {
        FileReader reader = new FileReader(filepath);

        if (reader.ready()) { // This will check if the file is ready to read0
            Scanner scan = new Scanner(reader);
            String line = "";
            while (scan.hasNext()) {
                line = line + scan.nextLine();
            }

            reader.close();

            // // checks the file is empty or not and parse the contents
            if (!line.equals("")) {
                reader.close();
                FileReader reader2 = new FileReader(filepath);
                record = (JSONObject) jsonParser.parse(reader2); // This will convert the contents of the file into jsonobject
                userlist = (JSONArray) record.get("users");
                reader2.close();
            }
        }

        this.dispose(); // This will close the current window
        Dashboard e = new Dashboard(); // This will open the dashboard window
        e.setVisible(true);
    }

    // This will save the record in the file path
    public static void save() throws IOException {
        FileWriter file = new FileWriter(filepath);
        file.write(record.toJSONString());
        file.close();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbttn;
    private javax.swing.JButton Clearbttn;
    private javax.swing.JButton Updatebttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jnewpass;
    private javax.swing.JTextField jnewuser;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JLabel jpasswordfield;
    private javax.swing.JTextField juser;
    private javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
